# Generated by Django 4.0.4 on 2022-05-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of user')),
            ],
            options={
                'verbose_name': 'Users of site',
                'verbose_name_plural': 'Users of site',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Data_encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(verbose_name='Original text')),
                ('open_key', models.CharField(max_length=15, verbose_name='Open key')),
                ('secret_key', models.CharField(max_length=15, verbose_name='Secret key')),
                ('encrypted_text', models.CharField(max_length=1000, verbose_name='Encrypted text')),
                ('data_time_encryption', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='encryption.users')),
            ],
            options={
                'verbose_name': "Data of user's encryption",
                'verbose_name_plural': "Data of user's encryption",
            },
        ),
    ]
