# Generated by Django 4.0.4 on 2022-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_encryption',
            options={'ordering': ['email'], 'verbose_name': "Data of user's encryption", 'verbose_name_plural': "Data of user's encryption"},
        ),
        migrations.RemoveField(
            model_name='data_encryption',
            name='user_email',
        ),
        migrations.AddField(
            model_name='data_encryption',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email of user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
